name: Build MiSTer Main and Tools

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: misterdevelop/mister-builder:latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      # === Build MiSTer ===
      - name: Build Main MiSTer
        run: make -j$(nproc)

      - name: Upload MiSTer binary
        uses: actions/upload-artifact@v3
        with:
          name: MiSTer-main
          path: ./MiSTer

      # === Build your tool (input_monitor or similar) ===
      - name: Build input_monitor tool
        run: |
          cd tools/input_monitor    # adjust if your code lives somewhere else
          make -j$(nproc) || ${CXX:-arm-none-linux-gnueabihf-g++} -O2 -Wall -o input_monitor input_monitor.cpp

      - name: Upload input_monitor binary
        uses: actions/upload-artifact@v3
        with:
          name: input-monitor
          path: tools/input_monitor/input_monitor
