name: Build MiSTer

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ARM cross-compiler (with symlinks)
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
          sudo ln -s /usr/bin/arm-linux-gnueabihf-gcc /usr/bin/arm-none-linux-gnueabihf-gcc
          sudo ln -s /usr/bin/arm-linux-gnueabihf-g++ /usr/bin/arm-none-linux-gnueabihf-g++

      - name: Build for MiSTer
        run: make -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mister-binaries
          path: bin/*
