name: Build MiSTer binaries

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ARM cross-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
          sudo ln -s /usr/bin/arm-linux-gnueabihf-gcc /usr/bin/arm-none-linux-gnueabihf-gcc
          sudo ln -s /usr/bin/arm-linux-gnueabihf-g++ /usr/bin/arm-none-linux-gnueabihf-g++

      - name: Build native x86 binary
        run: make clean && make CXX=g++ CC=gcc
      - name: Verify x86 binary
        run: file bin/* || true

      - name: Upload x86 artifact
        uses: actions/upload-artifact@v4
        with:
          name: mister-binary-x86
          path: bin/*

      - name: Build ARM (MiSTer) binary
        run: make clean && make CXX=arm-none-linux-gnueabihf-g++ CC=arm-none-linux-gnueabihf-gcc
      - name: Verify ARM binary
        run: file bin/* || true

      - name: Upload ARM artifact
        uses: actions/upload-artifact@v4
        with:
          name: mister-binary-arm
          path: bin/*
