name: Build MiSTer

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ARM cross-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: Build for MiSTer (ARM)
        run: make CROSS_COMPILE=arm-linux-gnueabihf-

      - name: Upload MiSTer binary
        uses: actions/upload-artifact@v4
        with:
          name: mister-binary
          path: bin/*    # adjust if your build output goes somewhere else
